; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

; Serial monitoring configuration
monitor_speed = 115200
monitor_filters = 
    colorize
    time
    esp32_exception_decoder

; Build configuration for debugging
build_type = debug
build_flags = 
    -DCORE_DEBUG_LEVEL=5
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    -DBOARD_HAS_PSRAM=0

; Hardware debugging
debug_tool = esp-builtin
debug_init_break = tbreak setup

lib_deps =
    ESP32Async/ESPAsyncWebServer@^3.6.0
    ESP32Async/AsyncTCP@^3.3.2
    madhephaestus/ESP32Servo@^3.0.5
board_build.filesystem = littlefs
board_build.partitions = default_8MB.csv

